# 开发环境配置
server:
  # 服务端口
  port: 8081
  servlet:
    # 项目contextPath
    context-path: /demo
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

  system:
  #第三方接口
  huiCalculatedOrderUrl: http://czqsg.top:8081/demo/check
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index

# 分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


# Spring配置
spring:

#  ##默认密码为空
#  redis:
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    jedis:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 100
#        # 连接池中的最小空闲连接
#        max-idle: 10
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 100000
#    # 连接超时时间（毫秒）
#    timeout: 5000
#    #默认是索引为0的数据库
#    database: 0


  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
